[build]
  command = "npm run build"
  functions = "api/**/*.ts"
  publish = ".next"

[[redirects]]
  from = "/"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
